// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"

	"github.com/99designs/gqlgen/graphql"
)

func (c *Comments) Items(ctx context.Context) (*Items, error) {
	result, err := c.Edges.ItemsOrErr()
	if IsNotLoaded(err) {
		result, err = c.QueryItems().Only(ctx)
	}
	return result, MaskNotFound(err)
}

func (i *Items) Comments(ctx context.Context) (result []*Comments, err error) {
	if fc := graphql.GetFieldContext(ctx); fc != nil && fc.Field.Alias != "" {
		result, err = i.NamedComments(graphql.GetFieldContext(ctx).Field.Alias)
	} else {
		result, err = i.Edges.CommentsOrErr()
	}
	if IsNotLoaded(err) {
		result, err = i.QueryComments().All(ctx)
	}
	return result, err
}
