// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"database/sql/driver"
	"fmt"
	"math"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Pacerino/pr0music/ent/comments"
	"github.com/Pacerino/pr0music/ent/items"
	"github.com/Pacerino/pr0music/ent/predicate"
)

// ItemsQuery is the builder for querying Items entities.
type ItemsQuery struct {
	config
	limit             *int
	offset            *int
	unique            *bool
	order             []OrderFunc
	fields            []string
	predicates        []predicate.Items
	withComments      *CommentsQuery
	modifiers         []func(*sql.Selector)
	loadTotal         []func(context.Context, []*Items) error
	withNamedComments map[string]*CommentsQuery
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the ItemsQuery builder.
func (iq *ItemsQuery) Where(ps ...predicate.Items) *ItemsQuery {
	iq.predicates = append(iq.predicates, ps...)
	return iq
}

// Limit adds a limit step to the query.
func (iq *ItemsQuery) Limit(limit int) *ItemsQuery {
	iq.limit = &limit
	return iq
}

// Offset adds an offset step to the query.
func (iq *ItemsQuery) Offset(offset int) *ItemsQuery {
	iq.offset = &offset
	return iq
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (iq *ItemsQuery) Unique(unique bool) *ItemsQuery {
	iq.unique = &unique
	return iq
}

// Order adds an order step to the query.
func (iq *ItemsQuery) Order(o ...OrderFunc) *ItemsQuery {
	iq.order = append(iq.order, o...)
	return iq
}

// QueryComments chains the current query on the "comments" edge.
func (iq *ItemsQuery) QueryComments() *CommentsQuery {
	query := &CommentsQuery{config: iq.config}
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := iq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := iq.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(items.Table, items.FieldID, selector),
			sqlgraph.To(comments.Table, comments.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, items.CommentsTable, items.CommentsColumn),
		)
		fromU = sqlgraph.SetNeighbors(iq.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// First returns the first Items entity from the query.
// Returns a *NotFoundError when no Items was found.
func (iq *ItemsQuery) First(ctx context.Context) (*Items, error) {
	nodes, err := iq.Limit(1).All(ctx)
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{items.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (iq *ItemsQuery) FirstX(ctx context.Context) *Items {
	node, err := iq.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first Items ID from the query.
// Returns a *NotFoundError when no Items ID was found.
func (iq *ItemsQuery) FirstID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = iq.Limit(1).IDs(ctx); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{items.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (iq *ItemsQuery) FirstIDX(ctx context.Context) int {
	id, err := iq.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single Items entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one Items entity is found.
// Returns a *NotFoundError when no Items entities are found.
func (iq *ItemsQuery) Only(ctx context.Context) (*Items, error) {
	nodes, err := iq.Limit(2).All(ctx)
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{items.Label}
	default:
		return nil, &NotSingularError{items.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (iq *ItemsQuery) OnlyX(ctx context.Context) *Items {
	node, err := iq.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only Items ID in the query.
// Returns a *NotSingularError when more than one Items ID is found.
// Returns a *NotFoundError when no entities are found.
func (iq *ItemsQuery) OnlyID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = iq.Limit(2).IDs(ctx); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{items.Label}
	default:
		err = &NotSingularError{items.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (iq *ItemsQuery) OnlyIDX(ctx context.Context) int {
	id, err := iq.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of ItemsSlice.
func (iq *ItemsQuery) All(ctx context.Context) ([]*Items, error) {
	if err := iq.prepareQuery(ctx); err != nil {
		return nil, err
	}
	return iq.sqlAll(ctx)
}

// AllX is like All, but panics if an error occurs.
func (iq *ItemsQuery) AllX(ctx context.Context) []*Items {
	nodes, err := iq.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of Items IDs.
func (iq *ItemsQuery) IDs(ctx context.Context) ([]int, error) {
	var ids []int
	if err := iq.Select(items.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (iq *ItemsQuery) IDsX(ctx context.Context) []int {
	ids, err := iq.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (iq *ItemsQuery) Count(ctx context.Context) (int, error) {
	if err := iq.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return iq.sqlCount(ctx)
}

// CountX is like Count, but panics if an error occurs.
func (iq *ItemsQuery) CountX(ctx context.Context) int {
	count, err := iq.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (iq *ItemsQuery) Exist(ctx context.Context) (bool, error) {
	if err := iq.prepareQuery(ctx); err != nil {
		return false, err
	}
	return iq.sqlExist(ctx)
}

// ExistX is like Exist, but panics if an error occurs.
func (iq *ItemsQuery) ExistX(ctx context.Context) bool {
	exist, err := iq.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the ItemsQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (iq *ItemsQuery) Clone() *ItemsQuery {
	if iq == nil {
		return nil
	}
	return &ItemsQuery{
		config:       iq.config,
		limit:        iq.limit,
		offset:       iq.offset,
		order:        append([]OrderFunc{}, iq.order...),
		predicates:   append([]predicate.Items{}, iq.predicates...),
		withComments: iq.withComments.Clone(),
		// clone intermediate query.
		sql:    iq.sql.Clone(),
		path:   iq.path,
		unique: iq.unique,
	}
}

// WithComments tells the query-builder to eager-load the nodes that are connected to
// the "comments" edge. The optional arguments are used to configure the query builder of the edge.
func (iq *ItemsQuery) WithComments(opts ...func(*CommentsQuery)) *ItemsQuery {
	query := &CommentsQuery{config: iq.config}
	for _, opt := range opts {
		opt(query)
	}
	iq.withComments = query
	return iq
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		CreatedAt time.Time `json:"created_at,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.Items.Query().
//		GroupBy(items.FieldCreatedAt).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
func (iq *ItemsQuery) GroupBy(field string, fields ...string) *ItemsGroupBy {
	grbuild := &ItemsGroupBy{config: iq.config}
	grbuild.fields = append([]string{field}, fields...)
	grbuild.path = func(ctx context.Context) (prev *sql.Selector, err error) {
		if err := iq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		return iq.sqlQuery(ctx), nil
	}
	grbuild.label = items.Label
	grbuild.flds, grbuild.scan = &grbuild.fields, grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		CreatedAt time.Time `json:"created_at,omitempty"`
//	}
//
//	client.Items.Query().
//		Select(items.FieldCreatedAt).
//		Scan(ctx, &v)
func (iq *ItemsQuery) Select(fields ...string) *ItemsSelect {
	iq.fields = append(iq.fields, fields...)
	selbuild := &ItemsSelect{ItemsQuery: iq}
	selbuild.label = items.Label
	selbuild.flds, selbuild.scan = &iq.fields, selbuild.Scan
	return selbuild
}

// Aggregate returns a ItemsSelect configured with the given aggregations.
func (iq *ItemsQuery) Aggregate(fns ...AggregateFunc) *ItemsSelect {
	return iq.Select().Aggregate(fns...)
}

func (iq *ItemsQuery) prepareQuery(ctx context.Context) error {
	for _, f := range iq.fields {
		if !items.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if iq.path != nil {
		prev, err := iq.path(ctx)
		if err != nil {
			return err
		}
		iq.sql = prev
	}
	return nil
}

func (iq *ItemsQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*Items, error) {
	var (
		nodes       = []*Items{}
		_spec       = iq.querySpec()
		loadedTypes = [1]bool{
			iq.withComments != nil,
		}
	)
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*Items).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &Items{config: iq.config}
		nodes = append(nodes, node)
		node.Edges.loadedTypes = loadedTypes
		return node.assignValues(columns, values)
	}
	if len(iq.modifiers) > 0 {
		_spec.Modifiers = iq.modifiers
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, iq.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	if query := iq.withComments; query != nil {
		if err := iq.loadComments(ctx, query, nodes,
			func(n *Items) { n.Edges.Comments = []*Comments{} },
			func(n *Items, e *Comments) { n.Edges.Comments = append(n.Edges.Comments, e) }); err != nil {
			return nil, err
		}
	}
	for name, query := range iq.withNamedComments {
		if err := iq.loadComments(ctx, query, nodes,
			func(n *Items) { n.appendNamedComments(name) },
			func(n *Items, e *Comments) { n.appendNamedComments(name, e) }); err != nil {
			return nil, err
		}
	}
	for i := range iq.loadTotal {
		if err := iq.loadTotal[i](ctx, nodes); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

func (iq *ItemsQuery) loadComments(ctx context.Context, query *CommentsQuery, nodes []*Items, init func(*Items), assign func(*Items, *Comments)) error {
	fks := make([]driver.Value, 0, len(nodes))
	nodeids := make(map[int]*Items)
	for i := range nodes {
		fks = append(fks, nodes[i].ID)
		nodeids[nodes[i].ID] = nodes[i]
		if init != nil {
			init(nodes[i])
		}
	}
	query.withFKs = true
	query.Where(predicate.Comments(func(s *sql.Selector) {
		s.Where(sql.InValues(items.CommentsColumn, fks...))
	}))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		fk := n.items_comments
		if fk == nil {
			return fmt.Errorf(`foreign-key "items_comments" is nil for node %v`, n.ID)
		}
		node, ok := nodeids[*fk]
		if !ok {
			return fmt.Errorf(`unexpected foreign-key "items_comments" returned %v for node %v`, *fk, n.ID)
		}
		assign(node, n)
	}
	return nil
}

func (iq *ItemsQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := iq.querySpec()
	if len(iq.modifiers) > 0 {
		_spec.Modifiers = iq.modifiers
	}
	_spec.Node.Columns = iq.fields
	if len(iq.fields) > 0 {
		_spec.Unique = iq.unique != nil && *iq.unique
	}
	return sqlgraph.CountNodes(ctx, iq.driver, _spec)
}

func (iq *ItemsQuery) sqlExist(ctx context.Context) (bool, error) {
	switch _, err := iq.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

func (iq *ItemsQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := &sqlgraph.QuerySpec{
		Node: &sqlgraph.NodeSpec{
			Table:   items.Table,
			Columns: items.Columns,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt,
				Column: items.FieldID,
			},
		},
		From:   iq.sql,
		Unique: true,
	}
	if unique := iq.unique; unique != nil {
		_spec.Unique = *unique
	}
	if fields := iq.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, items.FieldID)
		for i := range fields {
			if fields[i] != items.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
	}
	if ps := iq.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := iq.limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := iq.offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := iq.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (iq *ItemsQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(iq.driver.Dialect())
	t1 := builder.Table(items.Table)
	columns := iq.fields
	if len(columns) == 0 {
		columns = items.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if iq.sql != nil {
		selector = iq.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if iq.unique != nil && *iq.unique {
		selector.Distinct()
	}
	for _, p := range iq.predicates {
		p(selector)
	}
	for _, p := range iq.order {
		p(selector)
	}
	if offset := iq.offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := iq.limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// WithNamedComments tells the query-builder to eager-load the nodes that are connected to the "comments"
// edge with the given name. The optional arguments are used to configure the query builder of the edge.
func (iq *ItemsQuery) WithNamedComments(name string, opts ...func(*CommentsQuery)) *ItemsQuery {
	query := &CommentsQuery{config: iq.config}
	for _, opt := range opts {
		opt(query)
	}
	if iq.withNamedComments == nil {
		iq.withNamedComments = make(map[string]*CommentsQuery)
	}
	iq.withNamedComments[name] = query
	return iq
}

// ItemsGroupBy is the group-by builder for Items entities.
type ItemsGroupBy struct {
	config
	selector
	fields []string
	fns    []AggregateFunc
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Aggregate adds the given aggregation functions to the group-by query.
func (igb *ItemsGroupBy) Aggregate(fns ...AggregateFunc) *ItemsGroupBy {
	igb.fns = append(igb.fns, fns...)
	return igb
}

// Scan applies the group-by query and scans the result into the given value.
func (igb *ItemsGroupBy) Scan(ctx context.Context, v any) error {
	query, err := igb.path(ctx)
	if err != nil {
		return err
	}
	igb.sql = query
	return igb.sqlScan(ctx, v)
}

func (igb *ItemsGroupBy) sqlScan(ctx context.Context, v any) error {
	for _, f := range igb.fields {
		if !items.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("invalid field %q for group-by", f)}
		}
	}
	selector := igb.sqlQuery()
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := igb.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

func (igb *ItemsGroupBy) sqlQuery() *sql.Selector {
	selector := igb.sql.Select()
	aggregation := make([]string, 0, len(igb.fns))
	for _, fn := range igb.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(igb.fields)+len(igb.fns))
		for _, f := range igb.fields {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	return selector.GroupBy(selector.Columns(igb.fields...)...)
}

// ItemsSelect is the builder for selecting fields of Items entities.
type ItemsSelect struct {
	*ItemsQuery
	selector
	// intermediate query (i.e. traversal path).
	sql *sql.Selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (is *ItemsSelect) Aggregate(fns ...AggregateFunc) *ItemsSelect {
	is.fns = append(is.fns, fns...)
	return is
}

// Scan applies the selector query and scans the result into the given value.
func (is *ItemsSelect) Scan(ctx context.Context, v any) error {
	if err := is.prepareQuery(ctx); err != nil {
		return err
	}
	is.sql = is.ItemsQuery.sqlQuery(ctx)
	return is.sqlScan(ctx, v)
}

func (is *ItemsSelect) sqlScan(ctx context.Context, v any) error {
	aggregation := make([]string, 0, len(is.fns))
	for _, fn := range is.fns {
		aggregation = append(aggregation, fn(is.sql))
	}
	switch n := len(*is.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		is.sql.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		is.sql.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := is.sql.Query()
	if err := is.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
