// Code generated by ent, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// Comments is the predicate function for comments builders.
type Comments func(*sql.Selector)

// Items is the predicate function for items builders.
type Items func(*sql.Selector)
